export const MOTIVATIONAL_QUOTES = [
  'Disciplina supera motivação.',
  'Cada série te aproxima da melhor versão.',
  'Você não precisa ser perfeita. Precisa ser consistente.',
  'O corpo conquista o que a mente acredita.',
  'Hoje você faz o que outros não fazem. Amanhã conquista o que outros não conquistam.',
  'Não é sobre ser a melhor. É sobre ser melhor que ontem.',
  'Suar hoje, brilhar amanhã.',
  'A dor de hoje é a força de amanhã.',
  'Seu único limite é você mesma.',
  'Transformação começa no momento que você decide não desistir.',
  'Você é mais forte do que pensa.',
  'Um treino de cada vez. Um dia de cada vez.',
  'Progresso, não perfeição.',
  'Quem começa já tem coragem. Quem continua tem disciplina.',
  'Seu futuro eu vai te agradecer.',
  'Não existe atalho. Existe consistência.',
  'Grandes resultados exigem pequenos esforços diários.',
  'Quando der vontade de parar, lembre por que começou.',
  'A academia é o único lugar onde você fracassa pra subir.',
  'Dificuldade é o preço do progresso.',
];
