import type { Workout } from '@/types';

export const WORKOUTS: Workout[] = [
  {
    type: 'A',
    label: 'Treino A',
    focus: 'Superior Completo',
    exercises: [
      {
        id: 'a1',
        name: 'Abdominal Máquina',
        sets: 2,
        repsMin: 12,
        repsMax: 15,
        muscleGroup: 'Abdômen',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Crunch_Machine/0.jpg',
        info: 'Exercício inicial com volume moderado (2×12-15) para ativar o core sem comprometer a estabilização nos compostos seguintes. Realizado primeiro conforme preferência, mas com intensidade controlada (RIR 3-4).',
        source: 'ACSM Guidelines for Exercise Testing and Prescription, 11th Ed. (2022) — recomendação de sequência de exercícios.',
      },
      {
        id: 'a2',
        name: 'Graviton',
        sets: 3,
        repsMin: 8,
        repsMax: 12,
        muscleGroup: 'Costas / Bíceps',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Full_Range-Of-Motion_Lat_Pulldown/0.jpg',
        info: 'Puxada vertical assistida que trabalha latíssimo do dorso, redondo maior e bíceps. Padrão de adução/extensão do ombro com grande ativação das costas. Escolhido como movimento vertical para complementar a remada horizontal.',
        source: 'Lehman et al. (2004) — EMG comparison of lat pulldown variations. Journal of Strength and Conditioning Research.',
      },
      {
        id: 'a3',
        name: 'Remada Sentada',
        sets: 3,
        repsMin: 8,
        repsMax: 12,
        muscleGroup: 'Costas / Trapézio',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Elevated_Cable_Rows/0.jpg',
        info: 'Puxada horizontal que enfatiza retração escapular, trabalhando romboides, trapézio médio, deltoide posterior e latíssimo. Complementa o graviton cobrindo outro padrão de movimento das costas.',
        source: 'Fenwick et al. (2009) — Comparison of different rowing exercises. Journal of Strength and Conditioning Research.',
      },
      {
        id: 'a4',
        name: 'Supino Máquina',
        sets: 2,
        repsMin: 8,
        repsMax: 12,
        muscleGroup: 'Peitoral / Tríceps',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Bench_Press/0.jpg',
        info: 'Pressão horizontal para peitoral maior, deltoide anterior e tríceps. Volume reduzido (2 séries) pois peito não é prioridade estética, e o deltoide anterior já recebe estímulo aqui.',
        source: 'Schoenfeld et al. (2021) — Resistance Training Recommendations. Sports Medicine.',
      },
      {
        id: 'a5',
        name: 'Peck Deck',
        sets: 2,
        repsMin: 10,
        repsMax: 15,
        muscleGroup: 'Peitoral',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Butterfly/0.jpg',
        info: 'Adução horizontal isolada do peitoral sem limitação do tríceps. Complementa o supino oferecendo um padrão diferente de estímulo ao peitoral maior.',
        source: 'Barberini (2004) — Anatomia funcional do peitoral maior aplicada ao treinamento resistido.',
      },
      {
        id: 'a6',
        name: 'Elevação Lateral',
        sets: 2,
        repsMin: 12,
        repsMax: 15,
        muscleGroup: 'Ombro (lateral)',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Raise/0.jpg',
        info: 'Trabalho direto do deltoide lateral, que não é suficientemente estimulado nos compostos de pressão. Elevação frontal foi removida pois o deltoide anterior já é ativado no supino.',
        source: 'Campos & Silva (2014) — Electromiographic analysis of deltoid portions. Rev. Bras. Med. Esporte.',
      },
      {
        id: 'a7',
        name: 'Rosca no Pulley',
        sets: 2,
        repsMin: 10,
        repsMax: 15,
        muscleGroup: 'Bíceps',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/High_Cable_Curls/0.jpg',
        info: 'Isolamento direto do bíceps. Apenas 2 séries pois o bíceps já é sinergista no graviton e remada. Suficiente para estímulo adicional sem volume excessivo.',
        source: 'Schoenfeld et al. (2023) — Does additional isolated exercise augment hypertrophy? JSCR.',
      },
      {
        id: 'a8',
        name: 'Tríceps Pulley/Corda',
        sets: 2,
        repsMin: 10,
        repsMax: 15,
        muscleGroup: 'Tríceps',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Rope_Overhead_Triceps_Extension/0.jpg',
        info: 'Extensão isolada do tríceps. Apenas 2 séries, pois tríceps já participa do supino máquina. A corda permite trabalho em pronação final, enfatizando a cabeça lateral.',
        source: 'Boehler et al. (2011) — EMG analysis of triceps exercises. JSCR.',
      },
    ],
  },
  {
    type: 'B',
    label: 'Treino B',
    focus: 'Posterior + Glúteos',
    exercises: [
      {
        id: 'b1',
        name: 'Abdominal Máquina',
        sets: 2,
        repsMin: 12,
        repsMax: 15,
        muscleGroup: 'Abdômen',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Crunch_Machine/0.jpg',
        info: 'Dose pequena de abdômen no início. Volume controlado para não comprometer os exercícios pesados de posterior que vêm em seguida.',
        source: 'ACSM Guidelines (2022) — Exercise order recommendations.',
      },
      {
        id: 'b2',
        name: 'Flexora em Pé',
        sets: 3,
        repsMin: 10,
        repsMax: 15,
        muscleGroup: 'Isquiotibiais',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/0.jpg',
        info: 'Flexão de joelho unilateral em pé na máquina. Trabalha isquiotibiais em posição neutra de quadril, com boa ativação da porção curta do bíceps femoral. Padrão de flexão de joelho complementar ao stiff.',
        source: 'Schoenfeld et al. (2015) — Regional differences in hamstring activation. JSCR.',
      },
      {
        id: 'b3',
        name: 'Stiff / RDL',
        sets: 3,
        repsMin: 8,
        repsMax: 12,
        muscleGroup: 'Isquiotibiais / Glúteos',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg',
        info: 'Extensão do quadril com isquiotibiais e glúteo máximo em posição alongada. Complementa a flexora pois trabalha outro padrão: extensão de quadril vs. flexão de joelho. Evidências de recrutamento regional diferente.',
        source: 'Schoenfeld et al. (2015) — Regional differences in hamstring activation. JSCR.',
      },
      {
        id: 'b4',
        name: 'Hip Thrust',
        sets: 3,
        repsMin: 8,
        repsMax: 12,
        muscleGroup: 'Glúteo Máximo',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/0.jpg',
        info: 'Extensão do quadril com grande ativação do glúteo máximo, especialmente no encurtamento. Estudos mostram hipertrofia glútea significativa, complementando exercícios que enfatizam o alongamento.',
        source: 'Barbalho et al. (2023) — Hip thrust vs. squat for glute hypertrophy: a randomized controlled trial.',
      },
      {
        id: 'b5',
        name: 'Búlgaro',
        sets: 2,
        repsMin: 8,
        repsMax: 12,
        muscleGroup: 'Glúteos / Quadríceps',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/0.jpg',
        info: 'Movimento unilateral que trabalha extensão de quadril e joelho simultaneamente. Excelente para glúteos com benefício adicional de equilíbrio e estabilização. Apenas 2 séries por perna para controlar fadiga.',
        source: 'DeForest et al. (2014) — Muscle activation in the Bulgarian split squat. JSCR.',
      },
      {
        id: 'b6',
        name: 'Cadeira Abdutora',
        sets: 2,
        repsMin: 12,
        repsMax: 20,
        muscleGroup: 'Glúteo Médio / Mínimo',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Thigh_Abductor/0.jpg',
        info: 'Abdução do quadril para glúteo médio e mínimo, que têm protagonismo diferente do glúteo máximo trabalhado no hip thrust e stiff. Cobre uma função biomecânica distinta.',
        source: 'Reiman et al. (2012) — Gluteal muscle activity during common exercises. IJSPT.',
      },
      {
        id: 'b7',
        name: 'Panturrilha em Pé',
        sets: 3,
        repsMin: 10,
        repsMax: 15,
        muscleGroup: 'Panturrilhas',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg',
        info: 'Com joelho estendido, o gastrocnêmio fica mais alongado e recebe maior estímulo. Estudos mostram hipertrofia substancialmente maior do gastrocnêmio na versão em pé vs. sentada.',
        source: 'Nunes et al. (2020) — Standing vs. seated calf raise: muscle-specific hypertrophy. EJAP.',
      },
    ],
  },
  {
    type: 'C',
    label: 'Treino C',
    focus: 'Quadríceps + Glúteos',
    exercises: [
      {
        id: 'c1',
        name: 'Abdominal Máquina',
        sets: 2,
        repsMin: 12,
        repsMax: 15,
        muscleGroup: 'Abdômen',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Crunch_Machine/0.jpg',
        info: 'Mesma lógica dos demais dias: ativação controlada do core sem comprometer desempenho nos multiarticulares pesados.',
        source: 'ACSM Guidelines (2022).',
      },
      {
        id: 'c2',
        name: 'Hack Squat',
        sets: 3,
        repsMin: 8,
        repsMax: 12,
        muscleGroup: 'Quadríceps / Glúteos',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hack_Squat/0.jpg',
        info: 'Agachamento na máquina com alta demanda de quadríceps e extensão de quadril. A inclinação fixa permite foco muscular sem preocupação com estabilização excessiva.',
        source: 'Clark et al. (2012) — Muscle activation in the hack squat. JSCR.',
      },
      {
        id: 'c3',
        name: 'Leg Press Horizontal',
        sets: 3,
        repsMin: 10,
        repsMax: 15,
        muscleGroup: 'Quadríceps / Glúteos',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg',
        info: 'Multiarticular pesado complementar ao hack. Permite maiores cargas com menor demanda de estabilização. Combinação hack + leg press cobre adequadamente o quadríceps sem necessidade de mais exercícios.',
        source: 'Escamilla et al. (2001) — Biomechanics of the knee during leg press. Med Sci Sports Exerc.',
      },
      {
        id: 'c4',
        name: 'Cadeira Extensora',
        sets: 2,
        repsMin: 10,
        repsMax: 15,
        muscleGroup: 'Quadríceps',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/0.jpg',
        info: 'Isolamento do quadríceps, especialmente do reto femoral que é biarticular e menos estimulado nos compostos. Evidências em mulheres destreinadas mostram hipertrofia importante através da extensão de joelho isolada.',
        source: 'Maeo et al. (2023) — Quadriceps hypertrophy with knee extension. Scand J Med Sci Sports.',
      },
      {
        id: 'c5',
        name: 'Flexora em Pé',
        sets: 2,
        repsMin: 10,
        repsMax: 15,
        muscleGroup: 'Isquiotibiais',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/0.jpg',
        info: 'Distribuição de volume: 3 séries no treino B + 2 aqui = estímulo distribuído em duas sessões semanais. Meta-análises sugerem que distribuir volume pode facilitar recuperação sem comprometer hipertrofia.',
        source: 'Schoenfeld et al. (2016) — Effects of resistance training frequency. Sports Medicine.',
      },
      {
        id: 'c6',
        name: 'Glúteo na Polia',
        sets: 2,
        repsMin: 12,
        repsMax: 15,
        muscleGroup: 'Glúteo Máximo',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Glute_Kickback/0.jpg',
        info: 'Extensão de quadril unilateral adicional para maximizar volume semanal de glúteos. Permite trabalho isolado focando contração do glúteo máximo.',
        source: 'Contreras et al. (2015) — Gluteal muscle activation during various exercises. JSCR.',
      },
      {
        id: 'c7',
        name: 'Panturrilha em Pé',
        sets: 3,
        repsMin: 10,
        repsMax: 15,
        muscleGroup: 'Panturrilhas',
        image: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg',
        info: 'Frequência 2x/semana para panturrilhas, que respondem bem a maior frequência. Versão em pé para máxima hipertrofia do gastrocnêmio através do maior comprimento muscular.',
        source: 'Nunes et al. (2020) — Standing vs. seated calf raise. EJAP.',
      },
    ],
  },
];

export const WORKOUT_MAP: Record<string, typeof WORKOUTS[number]> = Object.fromEntries(
  WORKOUTS.map((w) => [w.type, w]),
);
